<?php

/**
 * BaseTesis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property integer $id_autor
 * @property integer $tipo_id
 * @property Doctrine_Collection $Apartado
 * 
 * @method string              getTitulo()   Returns the current record's "titulo" value
 * @method integer             getIdAutor()  Returns the current record's "id_autor" value
 * @method integer             getTipoId()   Returns the current record's "tipo_id" value
 * @method Doctrine_Collection getApartado() Returns the current record's "Apartado" collection
 * @method Tesis               setTitulo()   Sets the current record's "titulo" value
 * @method Tesis               setIdAutor()  Sets the current record's "id_autor" value
 * @method Tesis               setTipoId()   Sets the current record's "tipo_id" value
 * @method Tesis               setApartado() Sets the current record's "Apartado" collection
 * 
 * @package    nuevo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTesis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tesis');
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('id_autor', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Apartado', array(
             'local' => 'id',
             'foreign' => 'tesis_id'));
    }
}