<?php

/**
 * BaseApartado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property string $introduccion
 * @property string $materiales
 * @property string $metodologia
 * @property string $procedimiento
 * @property string $resultados
 * @property string $conclusion
 * @property string $bibliografia
 * @property integer $tipo_id
 * @property integer $tesis_id
 * @property Tipo $Tipo
 * @property Tesis $Tesis
 * 
 * @method string   getTitulo()        Returns the current record's "titulo" value
 * @method string   getIntroduccion()  Returns the current record's "introduccion" value
 * @method string   getMateriales()    Returns the current record's "materiales" value
 * @method string   getMetodologia()   Returns the current record's "metodologia" value
 * @method string   getProcedimiento() Returns the current record's "procedimiento" value
 * @method string   getResultados()    Returns the current record's "resultados" value
 * @method string   getConclusion()    Returns the current record's "conclusion" value
 * @method string   getBibliografia()  Returns the current record's "bibliografia" value
 * @method integer  getTipoId()        Returns the current record's "tipo_id" value
 * @method integer  getTesisId()       Returns the current record's "tesis_id" value
 * @method Tipo     getTipo()          Returns the current record's "Tipo" value
 * @method Tesis    getTesis()         Returns the current record's "Tesis" value
 * @method Apartado setTitulo()        Sets the current record's "titulo" value
 * @method Apartado setIntroduccion()  Sets the current record's "introduccion" value
 * @method Apartado setMateriales()    Sets the current record's "materiales" value
 * @method Apartado setMetodologia()   Sets the current record's "metodologia" value
 * @method Apartado setProcedimiento() Sets the current record's "procedimiento" value
 * @method Apartado setResultados()    Sets the current record's "resultados" value
 * @method Apartado setConclusion()    Sets the current record's "conclusion" value
 * @method Apartado setBibliografia()  Sets the current record's "bibliografia" value
 * @method Apartado setTipoId()        Sets the current record's "tipo_id" value
 * @method Apartado setTesisId()       Sets the current record's "tesis_id" value
 * @method Apartado setTipo()          Sets the current record's "Tipo" value
 * @method Apartado setTesis()         Sets the current record's "Tesis" value
 * 
 * @package    nuevo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApartado extends Tesis
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('apartado');
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('introduccion', 'string', 50000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50000,
             ));
        $this->hasColumn('materiales', 'string', 50000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50000,
             ));
        $this->hasColumn('metodologia', 'string', 50000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50000,
             ));
        $this->hasColumn('procedimiento', 'string', 50000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50000,
             ));
        $this->hasColumn('resultados', 'string', 50000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50000,
             ));
        $this->hasColumn('conclusion', 'string', 50000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50000,
             ));
        $this->hasColumn('bibliografia', 'string', 50000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50000,
             ));
        $this->hasColumn('tipo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tesis_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipo', array(
             'local' => 'tipo_id',
             'foreign' => 'id'));

        $this->hasOne('Tesis', array(
             'local' => 'tesis_id',
             'foreign' => 'id'));
    }
}