<?php

/**
 * BaseTesisTema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property integer $id_tipo
 * @property integer $id_tesis
 * @property string $texto
 * @property Tipo $Tipo
 * @property Tesis $Tesis
 * 
 * @method string    getTitulo()   Returns the current record's "titulo" value
 * @method integer   getIdTipo()   Returns the current record's "id_tipo" value
 * @method integer   getIdTesis()  Returns the current record's "id_tesis" value
 * @method string    getTexto()    Returns the current record's "texto" value
 * @method Tipo      getTipo()     Returns the current record's "Tipo" value
 * @method Tesis     getTesis()    Returns the current record's "Tesis" value
 * @method TesisTema setTitulo()   Sets the current record's "titulo" value
 * @method TesisTema setIdTipo()   Sets the current record's "id_tipo" value
 * @method TesisTema setIdTesis()  Sets the current record's "id_tesis" value
 * @method TesisTema setTexto()    Sets the current record's "texto" value
 * @method TesisTema setTipo()     Sets the current record's "Tipo" value
 * @method TesisTema setTesis()    Sets the current record's "Tesis" value
 * 
 * @package    nuevo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTesisTema extends Tesis
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('tesis_tema');
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('id_tipo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_tesis', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('texto', 'string', 50000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tipo', array(
             'local' => 'id_tipo',
             'foreign' => 'id'));

        $this->hasOne('Tesis', array(
             'local' => 'id_tesis',
             'foreign' => 'id'));
    }
}