<?php

/**
 * BaseTipoTesis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tipo_id
 * @property integer $tesis_id
 * @property Tesis $Tesis
 * @property Tipo $Tipo
 * 
 * @method integer   getTipoId()   Returns the current record's "tipo_id" value
 * @method integer   getTesisId()  Returns the current record's "tesis_id" value
 * @method Tesis     getTesis()    Returns the current record's "Tesis" value
 * @method Tipo      getTipo()     Returns the current record's "Tipo" value
 * @method TipoTesis setTipoId()   Sets the current record's "tipo_id" value
 * @method TipoTesis setTesisId()  Sets the current record's "tesis_id" value
 * @method TipoTesis setTesis()    Sets the current record's "Tesis" value
 * @method TipoTesis setTipo()     Sets the current record's "Tipo" value
 * 
 * @package    nuevo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoTesis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_tesis');
        $this->hasColumn('tipo_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tesis_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tesis', array(
             'local' => 'tesis_id',
             'foreign' => 'id'));

        $this->hasOne('Tipo', array(
             'local' => 'tipo_id',
             'foreign' => 'id'));
    }
}