<?php

/**
 * BaseSeccionTesis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seccion_id
 * @property integer $tesis_id
 * @property Tesis $Tesis
 * @property Seccion $Seccion
 * 
 * @method integer      getSeccionId()  Returns the current record's "seccion_id" value
 * @method integer      getTesisId()    Returns the current record's "tesis_id" value
 * @method Tesis        getTesis()      Returns the current record's "Tesis" value
 * @method Seccion      getSeccion()    Returns the current record's "Seccion" value
 * @method SeccionTesis setSeccionId()  Sets the current record's "seccion_id" value
 * @method SeccionTesis setTesisId()    Sets the current record's "tesis_id" value
 * @method SeccionTesis setTesis()      Sets the current record's "Tesis" value
 * @method SeccionTesis setSeccion()    Sets the current record's "Seccion" value
 * 
 * @package    sf2013
 * @subpackage model
 * @author     Javi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeccionTesis extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seccion_tesis');
        $this->hasColumn('seccion_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tesis_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tesis', array(
             'local' => 'tesis_id',
             'foreign' => 'id'));

        $this->hasOne('Seccion', array(
             'local' => 'seccion_id',
             'foreign' => 'id'));
    }
}