<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/06/12 16:02:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=buena',
  'username' => 'roberto',
  'password' => 'roberto',
  'name' => 'doctrine',
)),);
