<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/12 18:23:12
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
