<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/06/12 18:22:56
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
