<?php

/**
 * ApartadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApartadoTable extends TesisTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApartadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Apartado');
    }
}