<?php

/**
 * AutorTesisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AutorTesisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AutorTesisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AutorTesis');
    }
}