<?php

/**
 * SeccionTesisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeccionTesisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeccionTesisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeccionTesis');
    }
}