<?php

/**
 * TesisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TesisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TesisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tesis');
    }
}