<?php

/**
 * TipoTesisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTesisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTesisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTesis');
    }
}