<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/06/12 16:02:09
$this->security = array (
  'new' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
